name: ci

run-name: "[${{ github.event.repository.name }}] Check: ${{ github.event_name == 'schedule' && 'scheduled' || github.event.pull_request.title }}"

on:
  pull_request:
    types: [opened, synchronize, reopened]
  schedule:
    - cron: "0 21 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
   build:
    runs-on:  ubuntu-24.04
    strategy:
      matrix:
        smalltalk: [ Pharo64-12, Pharo64-13 ]
    name: ${{ matrix.smalltalk }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Set up Smalltalk CI
        uses: hpi-swa/setup-smalltalkCI@85be4db1c16ce81ccb36c42d285e62e3fcdce893 # v1
        with:
          smalltalk-image: ${{ matrix.smalltalk }}
      - name: Load Image and Run Tests
        run: smalltalkci -s ${{ matrix.smalltalk }} .smalltalk.ston
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        timeout-minutes: 15
